/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "A_aliases.h"
#include "A.h"
#include "B_aliases.h"
#include "B.h"
#include "Joystick_Y_aliases.h"
#include "Joystick_Y.h"
#include "Joystick_X_aliases.h"
#include "Joystick_X.h"
#include "ADC_SAR_1.h"
#include "Control_Reg_1.h"
#include "Speaker_aliases.h"
#include "Speaker.h"
#include "ADC_SAR_Seq_1.h"
#include "h_sync_aliases.h"
#include "h_sync.h"
#include "v_sync_aliases.h"
#include "v_sync.h"
#include "CLK_PIN_aliases.h"
#include "CLK_PIN.h"
#include "Green_aliases.h"
#include "Green.h"
#include "Red_aliases.h"
#include "Red.h"
#include "Line_Int.h"
#include "DMA_1_dma.h"
#include "Control_Reg_2.h"
#include "Blue_aliases.h"
#include "Blue.h"
#include "VDAC8_1.h"
#include "GameTimer.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_Seq_1_SAR.h"
#include "ADC_SAR_Seq_1_IntClock.h"
#include "ADC_SAR_Seq_1_TempBuf_dma.h"
#include "ADC_SAR_Seq_1_FinalBuf_dma.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

